apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webappns
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 726681933704.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:4e60e9f
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.databasens.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_ROOT_PASSWORD
    - name: DATABASE
      value: "employees"
