apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: databasens
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 726681933704.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-repo:4e60e9f
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webappns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 726681933704.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:4e60e9f
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.databasens.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DATABASE
          value: "employees"
